### ISSUE TITLE
ClassCastException in strict mode

### ISSUE THREAD

**Issue by stickfigure** [PebbleTemplates/pebble#170]
I don't know quite exactly what is causing this, but when I set `.strictVariables(true)` I get a CCE. If this isn't enough, I can try to provide the template but it's a rather large email template (messy!). This is version 2.1.0 (it happened in 1.6.0 too).

```
java.lang.ClassCastException: com.mitchellbosecke.pebble.node.expression.GetAttributeExpression cannot be cast to com.mitchellbosecke.pebble.node.expression.ContextVariableExpression
	at com.mitchellbosecke.pebble.node.expression.GetAttributeExpression.evaluate(GetAttributeExpression.java:177)
	at com.mitchellbosecke.pebble.node.expression.FilterExpression.evaluate(FilterExpression.java:65)
	at com.mitchellbosecke.pebble.node.expression.FilterExpression.evaluate(FilterExpression.java:65)
	at com.mitchellbosecke.pebble.node.PrintNode.render(PrintNode.java:34)
	at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
	at com.mitchellbosecke.pebble.node.RootNode.render(RootNode.java:32)
	at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:107)
	at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:85)
```

**Comment by mbosecke** [comment]
I suspect you have an issue with your template but Pebble is failing to give a proper error message. I just made a commit that will help with the error message but it will not stop the fact that you are getting an error in the first place. 

Basically the error is trying to get an attribute from a null object, ex:
`{{ null.getName() }}`

With my recent commit it should at the very least give you a line number and the name of the attribute. 

If you get a chance to confirm that this helps, that'd be great. Feel free to wait until the next official Pebble release if you don't want to try the current snapshot; I don't mind keeping the task open.

**Comment by mbosecke** [comment]
For my own reference: ad15610ec36b4be1b1f63178c2baaaee10652b97

**Comment by mbosecke** [comment]
Closing due to inactivity and I suspect it's been fixed.
