### ISSUE TITLE
How to iterate over a sublist?

### ISSUE THREAD

**Issue by gitblit** [PebbleTemplates/pebble#192]
I'm using Pebble 1.6.0 (need to update my app framework to get on the current release).

I have a list of unknown length but I only want to iterate over the first 5 elements.
Here is what I am trying.
```
{% for item in items | slice(0, min(4, items.size)) %}
```

But this throws an exception:
```
Caused by: java.lang.IllegalArgumentException: Argument toIndex must be a number. Actual type: java.lang.Integer
	at com.mitchellbosecke.pebble.extension.core.SliceFilter.apply(SliceFilter.java:62)
	at com.mitchellbosecke.pebble.node.expression.FilterExpression.evaluate(FilterExpression.java:54)
```

Maybe...
- you've already fixed this in the 2.x releases?
- my syntax is incorrect?
- my assumption that Pebble can handle this expression is incorrect?

**Comment by gitblit** [comment]
Ah.  I think you've already fixed it.

> Bug fix: slice filter failed on integer argument
