### ISSUE TITLE
Exception '' is not an identifier.

### ISSUE THREAD

**Issue by jansorg** [PebbleTemplates/pebble#303]
When I edit a pebvariable annotation and remove the name value to enter a new one an exception is thrown.
```
{# @pebvariable name="" type="java.lang.Boolean" #}
```

```
'' is not an identifier.
com.intellij.util.IncorrectOperationException: '' is not an identifier.
	at com.intellij.psi.util.PsiUtil.checkIsIdentifier(PsiUtil.java:854)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createIdentifier(PsiElementFactoryImpl.java:561)
	at com.github.bjansen.intellij.pebble.psi.PebbleImplicitVariable.<init>(PebbleImplicitVariable.kt:9)
	at com.github.bjansen.intellij.pebble.psi.PebbleComment$Companion.getImplicitVariable(PebbleComment.kt:37)
	at com.github.bjansen.intellij.pebble.psi.PebbleFile$findLocalImplicitVariables$1.visitComment(PebbleFile.kt:47)
	at com.intellij.psi.impl.source.tree.PsiCoreCommentImpl.accept(PsiCoreCommentImpl.java:40)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:823)
	at com.github.bjansen.intellij.pebble.psi.PebbleFile.findLocalImplicitVariables(PebbleFile.kt:42)
	at com.github.bjansen.intellij.pebble.psi.PebbleFile.getImplicitVariables(PebbleFile.kt:23)
	at com.github.bjansen.intellij.pebble.psi.PebbleIdentifierReference.multiResolve(PebbleIdentifierReference.kt:32)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at com.github.bjansen.intellij.pebble.codeInspection.UnknownVariableInspection$buildVisitor$1.visitElement(UnknownVariableInspection.kt:49)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:70)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:286)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:254)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1132)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:234)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by jansorg** [comment]
Sorry, this should have been in the pebble IntelliJ template.
