### ISSUE TITLE
java.lang.IndexOutOfBoundsException when {% endblock %} removed from template

### ISSUE THREAD

**Issue by mtadmk** [PebbleTemplates/pebble#308]
We have 2 templates: 
- base
`{% block content %}{% endblock %}`
- extending
`{% extends "base::base.html" %}
{% block content %}
AAAA
{% endblock %}
`
after removing {% endblock %} from 'extending' we got exception with stack below. I believe it's bug as user should be given more specific answer about invalid template. Can you confirm?

pebble version: '2.4.0'

Exception encountered after removing {% endblock %} from valid template which I believe is a parser error:
`Caused by: java.lang.IndexOutOfBoundsException: Index: 44, Size: 44
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.mitchellbosecke.pebble.lexer.TokenStream.next(TokenStream.java:45)
	at com.mitchellbosecke.pebble.tokenParser.BlockTokenParser.parse(BlockTokenParser.java:60)
	at com.mitchellbosecke.pebble.parser.ParserImpl.subparse(ParserImpl.java:183)
	at com.mitchellbosecke.pebble.parser.ParserImpl.subparse(ParserImpl.java:94)
	at com.mitchellbosecke.pebble.parser.ParserImpl.parse(ParserImpl.java:86)
	at com.mitchellbosecke.pebble.PebbleEngine$1.call(PebbleEngine.java:131)
	at com.mitchellbosecke.pebble.PebbleEngine$1.call(PebbleEngine.java:120)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4793)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	... 118 common frames omitted`

**Comment by mtadmk** [comment]
Hey @ebussieres Can you take a look?

**Comment by satyadas2000** [comment]
error message should be thrown like "endblock tag does not exist with block tag", i have fixed the issue

**Comment by ebussieres** [comment]
You can submit a PR and i'll take a look

**Comment by satyadas2000** [comment]
Thanks
I am trying to push the changes , but it says permission denied. Can you
please help ?
$ git push origin issue308
fatal: AggregateException encountered.
   One or more errors occurred.
Username for 'https://github.com': satyadas2000
remote: Permission to PebbleTemplates/pebble.git denied to satyadas2000.
fatal: unable to access 'https://github.com/PebbleTemplates/pebble.git/':
The requested URL returned error: 403

thanks

**Comment by ebussieres** [comment]
You cannot push directly in the repository. You must first fork the
repository, create a branch and submit your PR

**Comment by ebussieres** [comment]
Fixed via #332
