### ISSUE TITLE
DelegatingLoader not Working with Spring Boot

### ISSUE THREAD

**Issue by MBurchard** [PebbleTemplates/pebble#312]
I initialize Pebble with this code:

	@Bean
	public PebbleEngine pebbleEngine() {
		return new PebbleEngine.Builder().extension(springExtension()).build();
	}

	@Bean
	public SpringExtension springExtension() {
		return new SpringExtension();
	}

	@Bean
	public ViewResolver viewResolver() {
		final PebbleViewResolver viewResolver = new PebbleViewResolver();
		viewResolver.setPrefix("/templates/");
		viewResolver.setSuffix(".twig");
		viewResolver.setPebbleEngine(pebbleEngine());
		return viewResolver;
	}

This is working very well, when running the project from Eclipse on a local Tomcat.

Running it with Spring Boot, as Java application, I get this Stacktrace:

	com.mitchellbosecke.pebble.error.LoaderException: Could not find template "index.html" (?:?)
		at com.mitchellbosecke.pebble.loader.DelegatingLoader.getReader(DelegatingLoader.java:74)
		at com.mitchellbosecke.pebble.loader.DelegatingLoader.getReader(DelegatingLoader.java:27)
		at com.mitchellbosecke.pebble.PebbleEngine.retrieveReaderFromLoader(PebbleEngine.java:173)
		at com.mitchellbosecke.pebble.PebbleEngine.access$300(PebbleEngine.java:52)
		at com.mitchellbosecke.pebble.PebbleEngine$1.call(PebbleEngine.java:126)
		at com.mitchellbosecke.pebble.PebbleEngine$1.call(PebbleEngine.java:120)
		at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4904)
		...

Any ideas why?

**Comment by ebussieres** [comment]
Where's your TemplateLoader ? See http://www.mitchellbosecke.com/pebble/documentation/guide/spring-integration
