### ISSUE TITLE
loop.length is not of type Number

### ISSUE THREAD

**Issue by ChristianCiach** [PebbleTemplates/pebble#362]
Since ~~Pebble 2.5~~ I've updated from 2.4.0 to 2.6.1,  I encounter this error:

```
Caused by: java.lang.RuntimeException: invalid operands for mathematical operation [SUBTRACT]
	at com.mitchellbosecke.pebble.utils.OperatorUtils.wideningConversionBinaryOperation(OperatorUtils.java:157)
	at com.mitchellbosecke.pebble.utils.OperatorUtils.subtract(OperatorUtils.java:56)
	at com.mitchellbosecke.pebble.node.expression.SubtractExpression.evaluate(SubtractExpression.java:21)
```
This is the statement inside the template:
`
{% if loop.index < ( loop.length - 1) %}`

This worked before. 

Using a debugger, I can see that "loop.length" is of type "ForNode$1" (whatever this may be), while "loop.index" is of type "Integer" (as expected).

**Comment by ebussieres** [comment]
Just made a fix and a release for this. It's gonna be available in a few minutes in central repository
