### ISSUE TITLE
 Support for Chinese variable syntax?

### ISSUE THREAD

**Issue by qiushasha** [PebbleTemplates/pebble#414]
### When set a chinese variable with template as this: {{商品名称}}, but cause a exception as bellow,
and I found some issues:
 1. The LexerImpl is not support Chinese variable syntax with  regular pattern as bellow:
  Pattern REGEX_NAME = Pattern.compile("^[a-zA-Z_][a-zA-Z0-9_]*"); 
 2.  The PebbleEngine  could give some APIs for user to implements her/she logic

Exception information:
com.mitchellbosecke.pebble.error.ParserException: Unexpected character [商] ({{商品名称}}:1)
	at com.mitchellbosecke.pebble.lexer.LexerImpl.lexExpression(LexerImpl.java:509)
	at com.mitchellbosecke.pebble.lexer.LexerImpl.lexPrint(LexerImpl.java:366)
	at com.mitchellbosecke.pebble.lexer.LexerImpl.tokenize(LexerImpl.java:181)
	at com.mitchellbosecke.pebble.PebbleEngine.getPebbleTemplate(PebbleEngine.java:157)
	at com.mitchellbosecke.pebble.PebbleEngine.lambda$getTemplate$1(PebbleEngine.java:146)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2039)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020)
..........................................

**Comment by ebussieres** [comment]
I really don't know nothing about Chinese syntax, so it's gonna be hard for me. Would you like to make a pull request for this ?

**Comment by qiushasha** [comment]
en，I will learn some code  and try to implement

**Comment by nil4u** [comment]
@qiushasha 为什么要用中文变量？ 不建议..

**Comment by yanxiyue** [comment]
@qiushasha 为什么要用中文变量？ 不建议...

**Comment by qiushasha** [comment]
@yanxiyue  at some cases, I need to build-in some  variables with chinese alias which can be convenient to user edit his/her template, so I hope PebbleEngine or Lexer give some extension points to implements some logic, but I don't know what to do

**Comment by ebussieres** [comment]
I'll close this for now. If you want to submit a PR for that, I'll gladly take a look at it
