### ISSUE TITLE
Release 3.1.5 doesn't work in Android

### ISSUE THREAD

**Issue by merlin-zaraza** [PebbleTemplates/pebble#580]
Seems like there are some regex patterns were added to release 3.1.5 which doesn't work in Android. Previous version (3.1.4) works well.
Here is stack trace:
```
Caused by java.util.regex.PatternSyntaxException: U_ILLEGAL_ARGUMENT_ERROR
^[\p{IsLetter}_][\p{IsLetter}\p{IsDigit}_]*
       at java.util.regex.Pattern.compileImpl(Pattern.java)
       at java.util.regex.Pattern.compile(Pattern.java:1344)
       at java.util.regex.Pattern.<init>(Pattern.java:1328)
       at java.util.regex.Pattern.compile(Pattern.java:950)
       at com.mitchellbosecke.pebble.lexer.LexerImpl.<clinit>(LexerImpl.java:2)
       at com.mitchellbosecke.pebble.PebbleEngine.getPebbleTemplate(PebbleEngine.java:11)
       at com.mitchellbosecke.pebble.PebbleEngine.lambda$getTemplate$2(PebbleEngine.java)
       at com.mitchellbosecke.pebble.PebbleEngine.lambda$getTemplate$2$PebbleEngine(PebbleEngine.java)
       at com.mitchellbosecke.pebble.-$$Lambda$PebbleEngine$RWC2jsSmCWn6HfuOZr1k4eoPeUE.apply(-.java:8)
       at j$.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:47)
       at j$.util.concurrent.ConcurrentMap$-EL.computeIfAbsent(ConcurrentMap.java:6)
       at com.mitchellbosecke.pebble.cache.template.ConcurrentMapTemplateCache.computeIfAbsent(ConcurrentMapTemplateCache.java:2)
       at com.mitchellbosecke.pebble.cache.template.ConcurrentMapTemplateCache.computeIfAbsent(ConcurrentMapTemplateCache.java)
       at com.mitchellbosecke.pebble.PebbleEngine.getTemplate(PebbleEngine.java:17)
       at com.mitchellbosecke.pebble.PebbleEngine.getTemplate(PebbleEngine.java:2)
```

According to this post [https://stackoverflow.com/questions/47922686/patternsyntaxexception-when-trying-to-validate-latin-characters](https://stackoverflow.com/questions/47922686/patternsyntaxexception-when-trying-to-validate-latin-characters) Android doesn't recognize `Is` aliases.

**Comment by ebussieres** [comment]
The regex in problem is `^[\p{IsLetter}_][\p{IsLetter}\p{IsDigit}_]*`

According to this spec (https://developer.android.com/reference/java/util/regex/Pattern), `IsDigit`can be replaced with `Digit`.
Unfortunately, there's nothing for `IsLetter`. I tried to replace it with Alpha but some unit tests are failing

**Comment by ebussieres** [comment]
@merlin-zaraza : Can you try the SNAPSHOT and tell me if it fixes your error ? I've no setup to test it with Android.

Here's how you can retrieve the SNAPSHOT in sonatype: 
https://pebbletemplates.io/wiki/guide/installation/

**Comment by merlin-zaraza** [comment]
Still not working in Android:
```
Caused by: java.util.regex.PatternSyntaxException: U_ILLEGAL_ARGUMENT_ERROR
	^[\p{IsAlphabetic}_][\p{IsAlphabetic}\p{Digit}_]*
	at java.util.regex.Pattern.compileImpl(Native Method)
	at java.util.regex.Pattern.compile(Pattern.java:1340)
	at java.util.regex.Pattern.<init>(Pattern.java:1324)
	at java.util.regex.Pattern.compile(Pattern.java:946)
	at com.mitchellbosecke.pebble.lexer.LexerImpl.<clinit>(LexerImpl.java:93)
```

**Comment by merlin-zaraza** [comment]
Seems like it's Android part so I've submitted bug to Android issue tracker [https://issuetracker.google.com/issues/181655428](https://issuetracker.google.com/issues/181655428).
Would be appreciate for workaround, maybe you can create regex pattern without aliases.

**Comment by objectProgrammer** [comment]
Unfortunately Android is not using real Java so they are not using the standard RegEx engine either but ICU instead. ICU has different naming for some things, your issue will be almost definitely not be resolved by Android. When I created the issue, I did take Android in to account so I'm not sure why it does not work for you. If I remember correctly, I even tested the pattern.

**Comment by objectProgrammer** [comment]
Which Android version is this? Because [the page](https://developer.android.com/reference/java/util/regex/Pattern#ubpc) ebusseries sent does say that `Is` prefix is supported for `Letter` and `Digit`.

**Comment by objectProgrammer** [comment]
It appears to have been solved in newer Android versions but to support older ones I added a static initializer check.

**Comment by ebussieres** [comment]
@merlin-zaraza Can you try the SNAPSHOT and tell me if it fixes your error ?

**Comment by merlin-zaraza** [comment]
> @merlin-zaraza Can you try the SNAPSHOT and tell me if it fixes your error ?

Works now. Thank you!
