### ISSUE TITLE
ParseException: Unexpected tag name

### ISSUE THREAD

**Issue by iceBear67** [PebbleTemplates/pebble#607]
A unittest for component :
```java
private static final PebbleEngine TEMPLATE_ENGINE = new PebbleEngine.Builder().build();
private String context = "A new repository has been added.\n" +
                "Name: {{ repository.full_name }}\n" +
                "Url: {% repository.html_url %}\n" +
                "Language: {% repository.language %}";
    @SneakyThrows
    public String render(Map<String,Object> data){
        PebbleTemplate compiledTemplate = TEMPLATE_ENGINE.getLiteralTemplate(context); < error
        try (StringWriter wr = new StringWriter()) {
            compiledTemplate.evaluate(wr, data);
            return wr.toString();
        }
    }
```
Exception:
```
Unexpected tag name "repository" (A new repository has been added.
Name: {{ repository.full_name }}
Url: {% repository.html_url %}
Language: {% repository.language %}:3)
com.mitchellbosecke.pebble.error.ParserException: Unexpected tag name "repository" (A new repository has been added.
Name: {{ repository.full_name }}
Url: {% repository.html_url %}
Language: {% repository.language %}:3)
	at com.mitchellbosecke.pebble.parser.ParserImpl.subparse(ParserImpl.java:192)
	at com.mitchellbosecke.pebble.parser.ParserImpl.subparse(ParserImpl.java:104)
	at com.mitchellbosecke.pebble.parser.ParserImpl.parse(ParserImpl.java:97)
	at com.mitchellbosecke.pebble.PebbleEngine.getPebbleTemplate(PebbleEngine.java:168)
	at com.mitchellbosecke.pebble.PebbleEngine.lambda$getTemplate$2(PebbleEngine.java:150)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.mitchellbosecke.pebble.cache.template.ConcurrentMapTemplateCache.computeIfAbsent(ConcurrentMapTemplateCache.java:24)
	at com.mitchellbosecke.pebble.cache.template.ConcurrentMapTemplateCache.computeIfAbsent(ConcurrentMapTemplateCache.java:9)
	at com.mitchellbosecke.pebble.PebbleEngine.getTemplate(PebbleEngine.java:150)
	at com.mitchellbosecke.pebble.PebbleEngine.getLiteralTemplate(PebbleEngine.java:132)
	at shito.api.data.ShitoTemplate.render(ShitoTemplate.java:39)
```

But, When I'm trying to test it standalone it won't get any error...
```java
    private static final PebbleEngine TEMPLATE_ENGINE = new PebbleEngine.Builder()
            .build();
    @Test
    public void onTest(){
        var t = TEMPLATE_ENGINE.getLiteralTemplate("A new repository has been added.\n" +
                "Name: {{ repository.full_name }}\n" +
                "Url: {{ repository.html_url }} \n" +
                "Language: {{ repository.language }}");
        var excepted = "A new repository has been added.\n" +
                "Name: iceBear67/ShitoUrl: https://github.com/iceBear67/Shito \n" +
                "Language: Java";
        try(var sw = new StringWriter()){
            t.evaluate(sw,new DelegatingMap(new JsonPathMap(JsonPath.parse(RenderTest.class.getClassLoader().getResourceAsStream("test.json"))),new HashMap<>()));
            Assertions.assertEquals(excepted,sw.toString());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```
Parameters are equal but why :(

**Comment by iceBear67** [comment]
Alright I just found that `{%` isn't `{{`
