### ISSUE TITLE
Backslash parsing fails in replace function in template

### ISSUE THREAD

**Issue by zhangyongxianggithub** [PebbleTemplates/pebble#670]
version：
```xml
            <dependency>
                <groupId>io.pebbletemplates</groupId>
                <artifactId>pebble-spring-boot-starter</artifactId>
                <version>3.2.1</version>
            </dependency>
```
template snippet:
`COMMENT='{{- comment | replace({'\':'\\'}) | replace({"'":"\'"}) | raw -}}'`
exception information:

> Exception in thread "main" io.pebbletemplates.pebble.error.ParserException: Unexpected character [\] (rules/ddl:7)
	at io.pebbletemplates.pebble.lexer.LexerImpl.tokenizeExpression(LexerImpl.java:509)
	at io.pebbletemplates.pebble.lexer.LexerImpl.tokenizeBetweenPrintDelimiters(LexerImpl.java:369)
	at io.pebbletemplates.pebble.lexer.LexerImpl.tokenize(LexerImpl.java:192)
	at io.pebbletemplates.pebble.PebbleEngine.getPebbleTemplate(PebbleEngine.java:164)
	at io.pebbletemplates.pebble.PebbleEngine.lambda$getTemplate$0(PebbleEngine.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.pebbletemplates.pebble.cache.template.ConcurrentMapTemplateCache.computeIfAbsent(ConcurrentMapTemplateCache.java:25)
	at io.pebbletemplates.pebble.cache.template.ConcurrentMapTemplateCache.computeIfAbsent(ConcurrentMapTemplateCache.java:10)
	at io.pebbletemplates.pebble.PebbleEngine.getTemplate(PebbleEngine.java:152)
	at io.pebbletemplates.pebble.PebbleEngine.getTemplate(PebbleEngine.java:123)

**Comment by ebussieres** [comment]
Please submit a valid test case demonstrating your issue

**Comment by zhangyongxianggithub** [comment]
> Please submit a valid test case demonstrating your issue

I have checked the source code，a single \ character really cannot be replaced, but if with other character, it can be replaced

**Comment by silviuvergoti** [comment]
I've encountered it, too.
If I double escape the template for Java and Pebble, I can replace only double backslashes.

```
@Test
    public void shouldReplaceSingleBackslashInString() throws Exception {
        // Setup
        PebbleEngine engine = new PebbleEngine.Builder().build();
        String templateSource = "{{ name | replace({ '\\\\':'' }) | raw }}"; // I would expect to have to escape both java and pebble
        PebbleTemplate template = engine.getLiteralTemplate(templateSource);
        String input = "a\\\\\\b\\\\c\\"; // Input string with 3, 2, 1 backslashes

        // Context
        var context = new java.util.HashMap<String, Object>();
        context.put("name", input);

        // When
        StringWriter writer = new StringWriter();
        template.evaluate(writer, context);
        String result = writer.toString();

        // Then
        assertEquals("abc", result);
    }
```

I'd expect "...'\\\\'...." to be converted by Java in "....'\\'...." and Pebble to consider it "....'\' ". Probably it has something to do with `unquoteAndUnescape`. @ebussieres, any suggestions?
